### PR TITLE
fix quotation for defaultmysql

### LINKED ISSUE #168: [Bug]: IndexService DefaultMysql
### Expected behavior

The same behaviour as in Pimcore 10. Without adding a custom order by no exception should be thrown

### Actual behavior

Upon loading the data a bad query gets generated which results in an exception.

The problem seems to be that the order by cols are now quoted/escaped (see https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/IndexService/ProductList/DefaultMysql.php#L621) whereas in pimcore 10 they were not quoted (https://github.com/pimcore/pimcore/blob/v10.6.9/bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php#L708)

This leads to queries like 
``SELECT SQL_CALC_FOUND_ROWS DISTINCT virtualProductId as id, priceSystemName 
FROM ecommerceframework_productindex_terracefinder_at_new a 
WHERE active = 1 AND virtualProductActive = 1 AND inProductList = 1 AND 1  AND (type = 'variant') AND (ok=1) AND (virtualProductId != id) GROUP BY virtualProductId, priceSystemName 
ORDER BY min(`name`) asc,min(`a.id`) ASC LIMIT 32``

Now, since the order by query part is escaped and cols might include identifiers/alias (https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/IndexService/ProductList/DefaultMysql.php#L600) the query fails

### Steps to reproduce

- Setup a DefaultMysql Tenant
- Use VARIANT_MODE_INCLUDE_PARENT_OBJECT
- Load the data without setting special OrderBy clauses

### PR DESCRIPTION
**Pull request by AlternateIf**
fixes #168

### CODE REVIEW

File: src/IndexService/ProductList/DefaultMysql/Dao.php [hunk 1]
```diff
@@ -299,4 +299,13 @@ public function getLastRecordCount(): int
...
     }
+
+    /**
+     * @param string $value
+     * @return string
+     */
+    public function quoteIdentifier($value)
+    {
+        return $this->db->quoteIdentifier($value);
+    }
```
Comment (blankse) [inline src/IndexService/ProductList/DefaultMysql/Dao.php]: We should use type hints instead of php docs
```suggestion
    public function quoteIdentifier(string $value): string
    {
        return $this->db->quoteIdentifier($value);
    }
```

Comment (AlternateIf) [reply src/IndexService/ProductList/DefaultMysql/Dao.php]: changed, thanks for reviewing

**Review by fashxp — APPROVED** [review]

**Comment by fashxp** [comment]
thx very much
