### PR TITLE
[Bug] Fix Installer

### LINKED ISSUE #55: [Bug]: Attributes are not built yet. Is the service properly configured to set an attribute factory? /  Table pimcore/object_store_ef_fd is corrupted. Please drop the table and recreate
### Expected behavior

Installation completed.

### Actual behavior

```
ERROR     [pimcore] RuntimeException: Attributes are not built yet. Is the service properly configured to set an attribute factory? in /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/Config/AbstractConfig.php:182
Stack trace:
#0 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/Worker/AbstractWorker.php(65): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig->getAttributes()
#1 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/IndexService.php(176): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\AbstractWorker->getIndexAttributes(true)
#2 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(53): Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\IndexService->getIndexAttributes(true)
#3 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php(43): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->buildOptions()
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/VarExport.php(44): Pimcore\Bundle\EcommerceFrameworkBundle\CoreExtensions\ClassDefinition\IndexFieldSelectionCombo->__construct()
#5 /var/www/html/var/classes/fieldcollections/SimilarityField.php(45): Pimcore\Model\DataObject\ClassDefinition\Data::__set_state(Array)
#6 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Fieldcollection/Definition.php(114): include('/var/www/html/v...')
#7 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/Tools/Installer.php(285): Pimcore\Model\DataObject\Fieldcollection\Definition::getByKey('SimilarityField')
#8 /var/www/html/vendor/pimcore/ecommerce-framework-bundle/src/Tools/Installer.php(170): Pimcore\Bundle\EcommerceFrameworkBundle\Tools\Installer->installFieldCollections()
#9 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(334): Pimcore\Bundle\EcommerceFrameworkBundle\Tools\Installer->install()
#10 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/Command/Bundle/InstallCommand.php(59): Pimcore\Extension\Bundle\PimcoreBundleManager->install(Object(Pimcore\Bundle\EcommerceFrameworkBundle\PimcoreEcommerceFrameworkBundle))
#11 /var/www/html/vendor/symfony/console/Command/Command.php(312): Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#19 /var/www/html/bin/console(20): require_once('/var/www/html/v...')
#20 {main}
```

```
[ERROR] An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1877 Table
         pimcore/object_store_ef_fd is corrupted. Please drop the table and recreate.
```

### Steps to reproduce

1. Install pimcore/pimcore 11.0.0-RC1.
2. php composer require pimcore/ecommerce-framework-bundle
3. In config/bundles.php add `PimcoreEcommerceFrameworkBundle::class => ['all' => true]`,
4. php bin/console pimcore:bundle:install PimcoreEcommerceFrameworkBundle

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this PR
Resolves #55 

## Additional Info
Fixing problems while installing with skeleton.
Making attributes nullable

### CODE REVIEW

File: src/IndexService/Config/AbstractConfig.php [hunk 1]
```diff
@@ -175,13 +175,8 @@ public function getTenantName(): string
      *
      * @return Attribute[]
```
Comment (blankse) [inline src/IndexService/Config/AbstractConfig.php]:
```suggestion
     * @return Attribute[]|null
```

or remove the php doc because its already defined in the interface.

Comment (mattamon) [reply src/IndexService/Config/AbstractConfig.php]: I thought about that, but tbh I don't want to start en remove Phpdoc only for this one. It would only make sense to do it as a whole.

Comment (blankse) [reply src/IndexService/Config/AbstractConfig.php]: Than you should add the `null` here also

File: src/IndexService/Config/AbstractConfig.php [hunk 2]
```diff
@@ -173,15 +173,10 @@ public function getTenantName(): string
     /**
      * Returns configured attributes for product index
      *
-     * @return Attribute[]
+     * @return Attribute[]|null
      */
-    public function getAttributes(): array
+    public function getAttributes(): ?array
```
Comment (dvesh3) [inline src/IndexService/Config/AbstractConfig.php]: why return null? `buildAttributes` called on constructor which should set the value already.

Comment (dvesh3) [reply src/IndexService/Config/AbstractConfig.php]: also remove legacy code from `getSearchAttributes`

Comment (mattamon) [reply src/IndexService/Config/AbstractConfig.php]: I initially only removed the legacy code here where the exception is thrown. Then I tried to install it again and got the following error message, hence why I made it nullable. 
In AbstractConfig.php line 180:
                                                                                                                                                  
  Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig::getAttributes(): Return value must be of type array, null returned  
                                                                 
Guess it has something to do with that it is declared nullable. We could also change that to an array instead of null? Something like this?
 /**
     * @var Attribute[]
     */
    protected array $attributes = [];

https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/IndexService/Config/AbstractConfig.php#L38

Comment (dvesh3) [reply src/IndexService/Config/AbstractConfig.php]: yes, I would try making it non-nullable

Comment (mattamon) [reply src/IndexService/Config/AbstractConfig.php]: Done

**Review by dvesh3 — APPROVED** [review]
