### PR TITLE
Set amount to the subtotal when the discount amount exceeds the subtotal

### LINKED ISSUE #199: [Bug]: Cart discount applied to the total price instead of the subtotal
### Expected behavior

The cart discount with a fixed amount only applies to the subtotal, meaning it does not affect price modifications like shipping costs.

### Actual behavior

The cart discount with fixed amount reduces the total cart price, including modifications like shipping costs. This behavior differs from percentage discounts, which only apply to the subtotal and do not affect additional costs.

### Steps to reproduce

Create a rule with a cart discount using a fixed amount. Then, purchase a product priced lower than the discount, and include a price modification that increases the total (e.g., shipping or payment fees). After applying the rule and the extra costs, the discount is applied to the total price, not just to the product(s) price.

Example:

2 products priced at 20€ + 10€ shipping = 30€. If you apply a 25€ discount, the total price will be 5€ (30€ - 25€), instead of the expected 10€. However, if you apply a 100% discount, the total price would be 10€, not 5€."

### PR DESCRIPTION
**Pull request by jan888adams**
The cart discount reduces the total cart price, including price modifications like shipping costs. This behavior differs from percentage discounts, which only apply to the subtotal and do not affect additional costs.

This is fixed by setting the discount amount to the subtotal when the discount amount exceeds the subtotal.

Resolves: #199

### CODE REVIEW

File: src/PricingManager/Action/CartDiscount.php [hunk 1]
```diff
@@ -32,14 +32,18 @@ public function executeOnCart(EnvironmentInterface $environment): ActionInterfac
...
+            // prevent discounted amount to be higher than the subtotal
+            $amount = $subTotal;
+        } elseif ($amount->isZero()) {
+            $amount = $subTotal->toPercentage($this->getPercent());
+            // round to 2 digits for further calculations to avoid rounding issues at later point
             $amount = Decimal::fromDecimal($amount->withScale(2));
         }
 
-        $amount = $amount->toAdditiveInverse();
+        $amount = $amount->mul(-1);
```
Comment (jdreesen) [inline src/PricingManager/Action/CartDiscount.php]: Why this change?

Comment (jan888adams) [reply src/PricingManager/Action/CartDiscount.php]: I didn't notice that

**Comment by fashxp** [comment]
Not sure, if we should make that behavior configurable?
Or at least we merge that for the next minor and add a upgrade note to it - since it is a change in behavior that someone could use the way it is right now. 

WDYT?

**Comment by jan888adams** [comment]
That sounds like a good idea. I would implement the current behavior as the default, with an option to switch to the new calculation. Additionally, I would apply the change only to the fixed amount and deprecate the old method of calculating cart discounts with fixed amounts.

**Comment by fashxp** [comment]
please just update the english translation file. the rest is translated via poeditor, see also https://pimcore.com/docs/platform/Pimcore/Multi_Language_i18n/Admin_Translations/#adding-your-own-admin-languages-since-v636

File: src/PricingManager/Action/CartDiscount.php [hunk 2]
```diff
@@ -28,15 +28,30 @@ class CartDiscount implements DiscountInterface, CartActionInterface
...
-            $amount = $priceCalculator->getSubTotal()->getAmount()->toPercentage($this->getPercent());
-            //round to 2 digits for further calculations to avoid rounding issues at later point
+        if ($subTotal->sub($amount)->isNegative()) {
+            // prevent discounted amount to be higher than the subtotal
+            $amount = $subTotal;
+        } elseif ($amount->isZero()) {
+            $amount = $subTotal->toPercentage($this->getPercent());
+            // round to 2 digits for further calculations to avoid rounding issues at later point
             $amount = Decimal::fromDecimal($amount->withScale(2));
+        } else {
```
Comment (fashxp) [inline src/PricingManager/Action/CartDiscount.php]: hmm, on second thought, I wouldn't deprecate the old way. As discussed, there might be use cases for that behavior too.

**Review by fashxp — CHANGES_REQUESTED** [review]

File: src/PricingManager/Action/CartDiscount.php (hunk 2 above)
Comment (jan888adams) [reply src/PricingManager/Action/CartDiscount.php]: No problem at all, I'll make the change. I also suggest we allow percentage-based cart discounts to be selectable, so they can apply either to the total or the subtotal. Currently, it always applies to the subtotal, but since it’s not an easy change, I would leave it for now.

Comment (fashxp) [reply src/PricingManager/Action/CartDiscount.php]: thank you very much! 
I agree for leaving out the percentage-based cart discounts for now

**Review by fashxp — APPROVED** [review]

**Comment by fashxp** [comment]
thanks again!
