### PR TITLE
[bugfix] Process two-dimensional arrays from DefaultBrickGetterSequen…

### LINKED ISSUE #150: [Bug]: Array to string conversion while product indexing
### Expected behavior

Product indexer works with all provided getters (also DefaultBrickGetterSequenceToMultiselect)

### Actual behavior

If in index_service configuration, the `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` is set, the exception is thrown:

> Exception in IndexService: ErrorException: Warning: Array to string conversion in /var/www/html/app/site/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/Worker/AbstractWorker.php

The DefaultBrickGetterSequenceToMultiselect getter returns a multidimensional array, which cannot be processed in implode() function in AbstractWorker->convertArray()

### Steps to reproduce

- Set `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` in index_service configuration
- Run indexer

### PR DESCRIPTION
**Pull request by 80Quattro**
…ceToMultiselect

Closes #150 

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

File: src/IndexService/Worker/AbstractWorker.php [hunk 1]
```diff
@@ -135,7 +135,18 @@ abstract protected function doDeleteFromIndex(int $subObjectId, IndexableInterfa
...
-            return WorkerInterface::MULTISELECT_DELIMITER . implode(WorkerInterface::MULTISELECT_DELIMITER, $data) . WorkerInterface::MULTISELECT_DELIMITER;
+            // One-dimensional array
+            if(count($data) == count($data, COUNT_RECURSIVE)) {
+                return WorkerInterface::MULTISELECT_DELIMITER . implode(WorkerInterface::MULTISELECT_DELIMITER, $data) . WorkerInterface::MULTISELECT_DELIMITER;
+            }
+
+            // Two-dimensional array
+            $string = WorkerInterface::MULTISELECT_DELIMITER;
+            foreach($data as $d) {
+                $string .= implode(WorkerInterface::MULTISELECT_DELIMITER, $d);
```
Comment (fashxp) [inline src/IndexService/Worker/AbstractWorker.php]: this is not working as intended. 

```php 
$data = [[1.1, 1.2], [2.1, 2.2]];
```

results in 

```
"#;#1.1#;#1.22.1#;#2.2#;#"
```

so the delimiter between the two sub arrays is missing.

Comment (fashxp) [reply src/IndexService/Worker/AbstractWorker.php]: on second though, I think that the better place to fix this might be in `DefaultBrickGetterSequenceToMultiselect` itself ... and make sure it returns already one dimensional arrays, WDYT?

**Review by fashxp — CHANGES_REQUESTED** [review]

File: src/IndexService/Worker/AbstractWorker.php (hunk 1 above)
Comment (80Quattro) [reply src/IndexService/Worker/AbstractWorker.php]: @fashxp thank you for the review & suggestions! I've reverted changes from AbstractWorker and adapted the DefaultBrickGetterSequenceToMultiselect. Hopefully it will work well now.

**Review by fashxp — APPROVED** [review]

**Comment by fashxp** [comment]
looks good to me now, thx very much!
