### PR TITLE
[Bug]: Add mandatory check on pricing rule conditions

### LINKED ISSUE #99: [Ecommerce][Bug] Empty mandatory fields does not prevent saving
# Bug Report
 
  
### Expected behavior 

Saving a Price Rule condition should not be possible when *mandatory* fields are empty.

### Actual behavior 

Saving works, no error messages or indications.

### Steps to reproduce  
  
Create a Price Rule condition with a mandatory field.
Save it.

### Code example 

If this field is left empty, the condition should not be saved, preferably an error message should be displayed.

```js
{
	xtype: "numberfield",
	fieldLabel: "Minimum quantity",
	labelWidth: 200,
	mandatory: true,
	name: "qty",
	maxValue: 100000,
	value: data.qty,
	width: 600,
}
```

### PR DESCRIPTION
**Pull request by kingjia90**
Resolves https://github.com/pimcore/ecommerce-framework-bundle/issues/99

Misses the red asterix 🤔 not sure yet where can be added

### CODE REVIEW

File: src/Resources/public/js/pricing/config/item.js [hunk 1]
```diff
@@ -362,24 +362,34 @@ pimcore.bundle.EcommerceFramework.pricing.config.item = Class.create({
...
                     else
                     {
-                        condition[ item.getName() ] = item.getValue();
+                        value = item.getValue();
+                        condition[ item.getName() ] = value;
 
                     }
+
+                    if (item.mandatory && (!value)){
+                        Ext.MessageBox.alert(t("error"), t("mandatory_field_empty"));
```
Comment (dvesh3) [inline src/Resources/public/js/pricing/config/item.js]: I would also include field-name in the error message as the asterisk is anyway missing.

**Review by dvesh3 — COMMENTED** [review]
Should we also prevent save based on mandatory check on server side?

File: src/Resources/public/js/pricing/config/item.js (hunk 1 above)
Comment (kingjia90) [reply src/Resources/public/js/pricing/config/item.js]: image

https://github.com/pimcore/ecommerce-framework-bundle/pull/123/commits/36eb2c132f35132cea9c031d34a714edb1555c17

Comment (kingjia90) [reply src/Resources/public/js/pricing/config/item.js]: the good is it avoids 
image

These fields actually were meant to be mandatory, otherwise would crash because it would be passing `null` to non-nullable property.

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
:cherries: picked on 1.0 https://github.com/pimcore/ecommerce-framework-bundle/commit/e7c0f80677ab79c5bf354781afe753297c937d1d
